### ISSUE TITLE
Typo-an

### ISSUE THREAD

**Issue by jwyoung** [agile-data-curation/IDCC-2016#3]
Suggested change. Original text: Finally, this presentation also provides a additional communication path between the team and a growing international community of data management and curation practitioners who are both contributing to and providing feedback on the concepts and materials being developed.

Proposed text: Finally, this presentation also provides _**an**_ additional communication path between the team and a growing international community of data management and curation practitioners who are both contributing to and providing feedback on the concepts and materials being developed.

**Comment by karlbenedict** [comment]
done
